name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.stye.cn", custom_domain = true },
  { pattern = "quay.stye.cn", custom_domain = true },
  { pattern = "gcr.stye.cn", custom_domain = true },
  { pattern = "k8s-gcr.stye.cn", custom_domain = true },
  { pattern = "k8s.stye.cn", custom_domain = true },
  { pattern = "ghcr.stye.cn", custom_domain = true },
  { pattern = "cloudsmith.stye.cn", custom_domain = true },
  { pattern = "ecr.stye.cn", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.stye.cn", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
[placement]
mode = "smart"